name: Change status to 'Done'

on:
    pull_request:
        branches: [develop]
        types: [closed]

jobs:
    change-status:
        runs-on: ubuntu-latest

        steps:
            - name: Set up
              uses: actions/checkout@v3

            - name: Get current date
              id: get_current_date
              run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')"

            - name: Get ID
              id: get_id
              run: |
                  PR_TITLE="${{ github.event.pull_request.title }}"
                  echo "title: $PR_TITLE"
                  ID=$(echo "$PR_TITLE" | grep -P '(?<=\[)(.*?)+(?=\])' -o)
                  echo "title id: $ID"

                  echo "ID=$ID" >> $GITHUB_OUTPUT

            - name: Filter database
              id: filter_database
              run: |
                  CARD_ID=$(curl -X POST 'https://api.notion.com/v1/databases/${{ secrets.NOTION_DATABASE }}/query' \
                    -H 'Authorization: '"${{ secrets.NOTION_TOKEN }}"'' \
                    -H 'Notion-Version: 2022-06-28' \
                    -H "Content-Type: application/json" \
                  --data '{
                    "filter": {
                      "property": "ID",
                      "formula": {
                        "string": {
                          "equals": "${{ steps.get_id.outputs.ID }}"
                        }
                      }
                    }
                  }' | jq '.results[0].id' | grep -P '(?<=\")(.*?)+(?=\")' -o)

                  echo "CARD_ID=$CARD_ID" >> $GITHUB_OUTPUT

            - name: Update notion status
              run: |
                  curl -X PATCH 'https://api.notion.com/v1/pages/${{ steps.filter_database.outputs.CARD_ID }}' \
                  -H 'Authorization: '"${{ secrets.NOTION_TOKEN }}"'' \
                  -H "Content-Type: application/json" \
                  -H "Notion-Version: 2022-06-28" \
                  -X PATCH \
                  --data '{
                    "properties": {
                      "상태": {
                        "status": {
                          "name": "Done"
                        }
                      },
                      "기간": {
                        "date": {
                            "end": $CURRENT_DATE
                        }
                      }
                    }
                  }'
