name: Change status to 'Done'

on:
    pull_request:
        branches: [develop, feature/**]
        types: [closed, synchronize]

jobs:
    change-status:
        runs-on: ubuntu-latest

        steps:
            - name: Set up
              uses: actions/checkout@v3

            - name: Get current date
              id: get_current_date
              run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

            - name: Get ID
              id: get_id
              run: |
                  PR_TITLE="${{ github.event.pull_request.title }}"
                  echo "title: $PR_TITLE"
                  ID=$(echo "$PR_TITLE" | grep -P '(?<=\[)(.*?)+(?=\])' -o)
                  echo "title id: $ID"

                  echo "ID=$ID" >> $GITHUB_OUTPUT

            - name: Filter database
              id: filter_database
              run: |
                  RESPONSE=$(curl 'https://api.notion.com/v1/databases/${{ secrets.NOTION_DATABASE }}/query' \
                    -H 'Authorization: '"${{ secrets.NOTION_TOKEN }}"'' \
                    -H 'Notion-Version: 2022-06-28' \
                    -H "Content-Type: application/json" \
                    -X POST \
                  --data '{
                    "filter": {
                      "property": "ID",
                      "formula": {
                        "string": {
                          "equals": "${{ steps.get_id.outputs.ID }}"
                        }
                      }
                    }
                  }')
                  CARD_ID=$(echo $RESPONSE | jq '.results[0].id' | grep -P '(?<=\")(.*?)+(?=\")' -o)
                  echo "card id: $CARD_ID"
                  START_DATE=$(echo $RESPONSE | jq '.results[0].properties."기간".date.start')
                  echo "start date: $START_DATE"

                  echo "CARD_ID=$CARD_ID" >> $GITHUB_OUTPUT
                  echo "START_DATE=$START_DATE" >> $GITHUB_OUTPUT

            - name: Update notion status
              run: |
                  curl 'https://api.notion.com/v1/pages/${{ steps.filter_database.outputs.CARD_ID }}' \
                    -X PATCH \
                    -H 'Authorization: '"${{ secrets.NOTION_TOKEN }}"'' \
                    -H "Content-Type: application/json" \
                    -H "Notion-Version: 2022-06-28" \
                  --data '{
                    "properties": {
                      "상태": {
                        "status": {
                          "name": "Done"
                        }
                      },
                      "기간": {
                        "date": {
                            "start": ${{ steps.filter_database.outputs.START_DATE }}
                            "end": "${{ steps.get_current_date.outputs.CURRENT_DATE }}"
                        }
                      }
                    }
                  }'
