name: Change status to 'In review'

on:
    pull_request:
        branches: [develop, feature/**]
        types: [opened, synchronize]

jobs:
    notion-status:
        runs-on: ubuntu-latest

        steps:
            - name: Set up
              uses: actions/checkout@v3

            - name: Get ID
              id: get_id
              run: |
                  PR_TITLE="${{ github.event.pull_request.title }}"
                  echo "title: $PR_TITLE"
                  ID=$(echo "$PR_TITLE" | grep -P '(?<=\[)(.*?)+(?=\])' -o)
                  echo "title id: $ID"

                  echo "ID=$ID" >> $GITHUB_OUTPUT

            - name: Filter database
              id: filter_database
              run: |
                  RESPONSE=`curl -X POST 'https://api.notion.com/v1/databases/${{ secrets.NOTION_DATABASE }}/query' \
                    -H 'Authorization: '"${{ secrets.NOTION_TOKEN }}"'' \
                    -H 'Notion-Version: 2022-06-28' \
                    -H "Content-Type: application/json" \
                  --data '{
                    "filter": {
                      "property": "ID",
                      "formula": {
                        "string": {
                          "equals": "${{ steps.get_id.outputs.ID }}"
                        }
                      }
                    }
                  }'`

                  echo "response: $RESPONSE.results[0].id"
                  echo "RESPONSE=$RESPONSE" >> $GITHUB_OUTPUT

            - name: Extract value using jq
              id: extract_value
              run: |
                  echo "$RESPONSE"
                  $VALUE=$(echo "$RESPONSE" | jq -r .results[0].id)

                  echo "CARD_ID=$VALUE" >> $GITHUB_OUTPUT

            - name: Update notion status
              run: |
                  curl https://api.notion.com/v1/pages/$CARD_ID \
                  -H 'Authorization: Bearer '"${{ secrets.NOTION_TOKEN }}"'' \
                  -H "Content-Type: application/json" \
                  -H "Notion-Version: 2022-06-28" \
                  -X PATCH \
                  --data '{
                    "properties": {
                      "상태": { "name": "In review" }
                    }
                  }
